### ISSUE TITLE
CGMES: Voltage Regulation on BusBarSection improperly imported for Bus/Branch model

### ISSUE THREAD

**Issue by jeandemanged** [powsybl/powsybl-core#3560]
### Describe the current behavior

Example case:
- Generator on 10 kV with voltage regulation enabled, 228 kV targetV at remote 225 kV BusBar Section BBS1 in TopologicalNode TN1
- BBS1 in TN1 connects only to BBS2 in TN2 via a closed retained switch
- Lines are connecting from TN2 to rest of the network

The generator is imported with voltage regulation enabled, regulating local terminal at 10 kV with 228 kV targetV, causing load flow convergence issues.

### Describe the expected behavior

to be defined:
- current practice in CGMES importer is to avoid defining fictitious equipment and instead try to find an equivalent terminal, however only one TopologicalNode is examined, other topological nodes connected via closed retained switches are ignored, but could be considered.
- the current practice may be considered flawed: in case topology is changed (switches opened or closed) the chosen terminal may not be the relevant one anymore. To solve this we could instead define a fictitious zero loads to represent busbar sections and use this fictitious load terminal to be the regulating terminal.
- or ultimately, disable the voltage control in case of failure to find a proper terminal.
- Longer term solutions could be to either add support of busbar sections model in bus/breaker topology kind (not just node/breaker), or allow configured buses to be used instead of equipment terminals

### Describe the steps

See example case.

### Environment

PowSyBl core 6.8.1

### Relevant Log Output

Could not find any relevant warning in the logs

### Extra Information

powsybl-open-loadflow users may want to change [parameter `minNominalVoltageTargetVoltageCheck`](https://powsybl.readthedocs.io/projects/powsybl-open-loadflow/en/latest/loadflow/parameters.html) from default 20 kV to 0 kV to disable the improperly imported voltage regulation and workaround the load flow convergence issue.

**Comment by marqueslanauja** [comment]
I realized this error while implementing the `1EQ_24SSH` changes, and I fixed it in the PR #3264 related to the generators. The issue was that, to obtain the default `targetV`, the generator’s terminal was used instead of its regulating terminal. Now, the default `targetV` is correctly obtained based on the generator’s regulating terminal.

**Comment by jeandemanged** [comment]
Hello @marqueslanauja,

Tried with latest version, the issue is still present in core 7.0.1.

I created a small network to reproduce the problem:
[issue_3560.zip](https://github.com/user-attachments/files/23561778/issue_3560.zip)

Here test network, the generator 'GEN' regulates busbar section 'VL2_400_BBS1':
![Image](https://github.com/user-attachments/assets/f1b3d2ea-115b-4dfd-be86-b5ebf570caee)

As far as I can see the problem lies in `RegulatingTerminalMapper#mapForVoltageControl`. Here it falls back to calling `TerminalMapping#findFromTopologicalNode` which does not find any terminal: this method considers only one TopologicalNode, and ignores other TopologicalNode-s connected via closed retained Switch-es. In the end it fails to find a proper equivalent regulating terminal.
